### ISSUE TITLE
dttm.timestamp() not recognized

### ISSUE THREAD

**Issue by a-nai** [sann05/python-currencycom#5]
>>> neworder=client.new_order('BTC/USD_LEVERAGE','BUY','MARKET',250.0,'1109999999077777',20);
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/a-nai/.local/lib/python3.8/site-packages/currencycom/client.py", line 642, in new_order
    expire_timestamp_epoch = self._to_epoch_miliseconds(expire_timestamp)
  File "/home/a-nai/.local/lib/python3.8/site-packages/currencycom/client.py", line 113, in _to_epoch_miliseconds
    return int(dttm.timestamp() * 1000)
AttributeError: 'int' object has no attribute 'timestamp'

**Comment by sann05** [comment]
Hi, 

20 is a number. Should be datetime

https://github.com/sann05/python-currencycom/blob/b2486e1984c71355de37c98e98a7d4eaa12e9353/currencycom/client.py#L556
